<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Oddify.Common.Presentation\Oddify.Common.Presentation.csproj" />
    <ProjectReference Include="..\Oddify.Modules.Apostas.Application\Oddify.Modules.Apostas.Application.csproj" />
    <ProjectReference Include="..\..\Analise\Oddify.Modules.Analise.IntegrationEvents\Oddify.Modules.Analise.IntegrationEvents.csproj" />
  </ItemGroup>
</Project>
