// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oddify.Modules.Apostas.Infrastructure.Database;

#nullable disable

namespace Oddify.Modules.Apostas.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApostasDbContext))]
    [Migration("20260805154458_Add_MovimentacaoDaBanca")]
    partial class Add_MovimentacaoDaBanca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("apostas")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.AnalisesDisponiveis.AnaliseDisponivelParaAposta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("JaUtilizada")
                        .HasColumnType("boolean")
                        .HasColumnName("ja_utilizada");

                    b.Property<string>("Mercado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mercado");

                    b.Property<decimal>("OddDeMercado")
                        .HasColumnType("numeric")
                        .HasColumnName("odd_de_mercado");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.Property<decimal>("ProbabilidadeConfirmada")
                        .HasColumnType("numeric")
                        .HasColumnName("probabilidade_confirmada");

                    b.Property<bool>("Reduzida")
                        .HasColumnType("boolean")
                        .HasColumnName("reduzida");

                    b.HasKey("Id")
                        .HasName("pk_analises_disponiveis_para_aposta");

                    b.ToTable("analises_disponiveis_para_aposta", "apostas");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.ApostasMultiplas.ApostaMultipla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em_utc");

                    b.Property<Guid>("BancaId")
                        .HasColumnType("uuid")
                        .HasColumnName("banca_id");

                    b.Property<DateTime>("CriadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em_utc");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<decimal?>("LucroOuPerda")
                        .HasColumnType("numeric")
                        .HasColumnName("lucro_ou_perda");

                    b.Property<decimal>("OddCombinada")
                        .HasColumnType("numeric")
                        .HasColumnName("odd_combinada");

                    b.Property<int>("Origem")
                        .HasColumnType("integer")
                        .HasColumnName("origem");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer")
                        .HasColumnName("resultado");

                    b.Property<decimal>("RetornoPotencial")
                        .HasColumnType("numeric")
                        .HasColumnName("retorno_potencial");

                    b.Property<decimal>("Stake")
                        .HasColumnType("numeric")
                        .HasColumnName("stake");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_apostas_multiplas");

                    b.HasIndex("BancaId")
                        .HasDatabaseName("ix_apostas_multiplas_banca_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_apostas_multiplas_usuario_id");

                    b.ToTable("apostas_multiplas", "apostas");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.Bancas.Banca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em_utc");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em_utc");

                    b.Property<bool>("ModoPaperTrading")
                        .HasColumnType("boolean")
                        .HasColumnName("modo_paper_trading");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PercentualPorEntrada")
                        .HasColumnType("numeric")
                        .HasColumnName("percentual_por_entrada");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_atual");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_inicial");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_bancas");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_bancas_usuario_id");

                    b.ToTable("bancas", "apostas");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.MovimentacoesDaBanca.MovimentacaoDaBanca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApostaMultiplaId")
                        .HasColumnType("uuid")
                        .HasColumnName("aposta_multipla_id");

                    b.Property<Guid>("BancaId")
                        .HasColumnType("uuid")
                        .HasColumnName("banca_id");

                    b.Property<DateTime>("CriadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em_utc");

                    b.Property<decimal>("SaldoAposMovimentacao")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_apos_movimentacao");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_movimentacoes_da_banca");

                    b.HasIndex("BancaId")
                        .HasDatabaseName("ix_movimentacoes_da_banca_banca_id");

                    b.ToTable("movimentacoes_da_banca", "apostas");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.PernasDeAposta.PernaDeAposta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnaliseId")
                        .HasColumnType("uuid")
                        .HasColumnName("analise_id");

                    b.Property<Guid>("ApostaMultiplaId")
                        .HasColumnType("uuid")
                        .HasColumnName("aposta_multipla_id");

                    b.Property<string>("Mercado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mercado");

                    b.Property<decimal>("Odd")
                        .HasColumnType("numeric")
                        .HasColumnName("odd");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer")
                        .HasColumnName("resultado");

                    b.HasKey("Id")
                        .HasName("pk_pernas_de_aposta");

                    b.HasIndex("ApostaMultiplaId")
                        .HasDatabaseName("ix_pernas_de_aposta_aposta_multipla_id");

                    b.ToTable("pernas_de_aposta", "apostas");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.ApostasMultiplas.ApostaMultipla", b =>
                {
                    b.HasOne("Oddify.Modules.Apostas.Domain.Bancas.Banca", null)
                        .WithMany()
                        .HasForeignKey("BancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_apostas_multiplas_bancas_banca_id");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.MovimentacoesDaBanca.MovimentacaoDaBanca", b =>
                {
                    b.HasOne("Oddify.Modules.Apostas.Domain.Bancas.Banca", null)
                        .WithMany()
                        .HasForeignKey("BancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_da_banca_bancas_banca_id");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.PernasDeAposta.PernaDeAposta", b =>
                {
                    b.HasOne("Oddify.Modules.Apostas.Domain.ApostasMultiplas.ApostaMultipla", null)
                        .WithMany()
                        .HasForeignKey("ApostaMultiplaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pernas_de_aposta_apostas_multiplas_aposta_multipla_id");
                });
#pragma warning restore 612, 618
        }
    }
}
