// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oddify.Modules.Apostas.Infrastructure.Database;

#nullable disable

namespace Oddify.Modules.Apostas.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApostasDbContext))]
    [Migration("20260818013049_Add_Outbox_And_Inbox")]
    partial class Add_Outbox_And_Inbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("apostas")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oddify.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("OccurredOnUtc", "ProcessedOnUtc")
                        .HasDatabaseName("idx_inbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("OccurredOnUtc", "ProcessedOnUtc"), new[] { "Id", "Type", "Content" });

                    b.ToTable("inbox_messages", "apostas");
                });

            modelBuilder.Entity("Oddify.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "apostas");
                });

            modelBuilder.Entity("Oddify.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOnUtc", "ProcessedOnUtc")
                        .HasDatabaseName("idx_outbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("OccurredOnUtc", "ProcessedOnUtc"), new[] { "Id", "Type", "Content" });

                    b.ToTable("outbox_messages", "apostas");
                });

            modelBuilder.Entity("Oddify.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "apostas");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.AnalisesDisponiveis.AnaliseDisponivelParaAposta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("JaUtilizada")
                        .HasColumnType("boolean")
                        .HasColumnName("ja_utilizada");

                    b.Property<string>("Mercado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mercado");

                    b.Property<decimal>("OddDeMercado")
                        .HasColumnType("numeric")
                        .HasColumnName("odd_de_mercado");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.Property<decimal>("ProbabilidadeConfirmada")
                        .HasColumnType("numeric")
                        .HasColumnName("probabilidade_confirmada");

                    b.Property<bool>("Reduzida")
                        .HasColumnType("boolean")
                        .HasColumnName("reduzida");

                    b.HasKey("Id")
                        .HasName("pk_analises_disponiveis_para_aposta");

                    b.ToTable("analises_disponiveis_para_aposta", "apostas");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.ApostasMultiplas.ApostaMultipla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em_utc");

                    b.Property<Guid>("BancaId")
                        .HasColumnType("uuid")
                        .HasColumnName("banca_id");

                    b.Property<DateTime>("CriadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em_utc");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<decimal?>("LucroOuPerda")
                        .HasColumnType("numeric")
                        .HasColumnName("lucro_ou_perda");

                    b.Property<decimal>("OddCombinada")
                        .HasColumnType("numeric")
                        .HasColumnName("odd_combinada");

                    b.Property<int>("Origem")
                        .HasColumnType("integer")
                        .HasColumnName("origem");

                    b.Property<Guid?>("PassoDaJornadaId")
                        .HasColumnType("uuid")
                        .HasColumnName("passo_da_jornada_id");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer")
                        .HasColumnName("resultado");

                    b.Property<decimal>("RetornoPotencial")
                        .HasColumnType("numeric")
                        .HasColumnName("retorno_potencial");

                    b.Property<decimal>("Stake")
                        .HasColumnType("numeric")
                        .HasColumnName("stake");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_apostas_multiplas");

                    b.HasIndex("BancaId")
                        .HasDatabaseName("ix_apostas_multiplas_banca_id");

                    b.HasIndex("PassoDaJornadaId")
                        .HasDatabaseName("ix_apostas_multiplas_passo_da_jornada_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_apostas_multiplas_usuario_id");

                    b.ToTable("apostas_multiplas", "apostas");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.Bancas.Banca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em_utc");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em_utc");

                    b.Property<int>("Finalidade")
                        .HasColumnType("integer")
                        .HasColumnName("finalidade");

                    b.Property<bool>("ModoPaperTrading")
                        .HasColumnType("boolean")
                        .HasColumnName("modo_paper_trading");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PercentualPorEntrada")
                        .HasColumnType("numeric")
                        .HasColumnName("percentual_por_entrada");

                    b.Property<int>("PerfilDeRisco")
                        .HasColumnType("integer")
                        .HasColumnName("perfil_de_risco");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_atual");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_inicial");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_bancas");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_bancas_usuario_id");

                    b.ToTable("bancas", "apostas");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.JornadasDeAlavancagem.FaixaDeMetaCatalogo", b =>
                {
                    b.Property<int>("Faixa")
                        .HasColumnType("integer")
                        .HasColumnName("faixa");

                    b.Property<int>("Multiplicador")
                        .HasColumnType("integer")
                        .HasColumnName("multiplicador");

                    b.Property<int>("NumeroDeFracoes")
                        .HasColumnType("integer")
                        .HasColumnName("numero_de_fracoes");

                    b.Property<int>("TotalDePassos")
                        .HasColumnType("integer")
                        .HasColumnName("total_de_passos");

                    b.HasKey("Faixa")
                        .HasName("pk_faixas_de_meta_catalogo");

                    b.ToTable("faixas_de_meta_catalogo", "apostas");

                    b.HasData(
                        new
                        {
                            Faixa = 0,
                            Multiplicador = 2,
                            NumeroDeFracoes = 3,
                            TotalDePassos = 3
                        },
                        new
                        {
                            Faixa = 1,
                            Multiplicador = 3,
                            NumeroDeFracoes = 3,
                            TotalDePassos = 5
                        },
                        new
                        {
                            Faixa = 2,
                            Multiplicador = 5,
                            NumeroDeFracoes = 4,
                            TotalDePassos = 8
                        });
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.JornadasDeAlavancagem.JornadaDeAlavancagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em_utc");

                    b.Property<Guid>("BancaId")
                        .HasColumnType("uuid")
                        .HasColumnName("banca_id");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em_utc");

                    b.Property<int>("FaixaMeta")
                        .HasColumnType("integer")
                        .HasColumnName("faixa_meta");

                    b.Property<int>("NumeroDeFracoes")
                        .HasColumnType("integer")
                        .HasColumnName("numero_de_fracoes");

                    b.Property<int>("PassoAtual")
                        .HasColumnType("integer")
                        .HasColumnName("passo_atual");

                    b.Property<decimal>("ProbabilidadeDeConclusao")
                        .HasColumnType("numeric")
                        .HasColumnName("probabilidade_de_conclusao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalDePassos")
                        .HasColumnType("integer")
                        .HasColumnName("total_de_passos");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("ValorInicial")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_inicial");

                    b.Property<decimal>("ValorObjetivo")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_objetivo");

                    b.HasKey("Id")
                        .HasName("pk_jornadas_de_alavancagem");

                    b.HasIndex("BancaId")
                        .HasDatabaseName("ix_jornadas_de_alavancagem_banca_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_jornadas_de_alavancagem_usuario_id");

                    b.ToTable("jornadas_de_alavancagem", "apostas");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.MovimentacoesDaBanca.MovimentacaoDaBanca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApostaMultiplaId")
                        .HasColumnType("uuid")
                        .HasColumnName("aposta_multipla_id");

                    b.Property<Guid>("BancaId")
                        .HasColumnType("uuid")
                        .HasColumnName("banca_id");

                    b.Property<DateTime>("CriadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em_utc");

                    b.Property<decimal>("SaldoAposMovimentacao")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_apos_movimentacao");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_movimentacoes_da_banca");

                    b.HasIndex("BancaId")
                        .HasDatabaseName("ix_movimentacoes_da_banca_banca_id");

                    b.ToTable("movimentacoes_da_banca", "apostas");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.PassosDaJornada.PassoDaJornada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em_utc");

                    b.Property<Guid>("JornadaId")
                        .HasColumnType("uuid")
                        .HasColumnName("jornada_id");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<int>("NumeroDeApostas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_de_apostas");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorDoPasso")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_do_passo");

                    b.Property<decimal?>("ValorResultante")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_resultante");

                    b.HasKey("Id")
                        .HasName("pk_passos_da_jornada");

                    b.HasIndex("JornadaId")
                        .HasDatabaseName("ix_passos_da_jornada_jornada_id");

                    b.ToTable("passos_da_jornada", "apostas");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.PernasDeAposta.PernaDeAposta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnaliseId")
                        .HasColumnType("uuid")
                        .HasColumnName("analise_id");

                    b.Property<Guid>("ApostaMultiplaId")
                        .HasColumnType("uuid")
                        .HasColumnName("aposta_multipla_id");

                    b.Property<string>("Mercado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mercado");

                    b.Property<decimal>("Odd")
                        .HasColumnType("numeric")
                        .HasColumnName("odd");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer")
                        .HasColumnName("resultado");

                    b.HasKey("Id")
                        .HasName("pk_pernas_de_aposta");

                    b.HasIndex("ApostaMultiplaId")
                        .HasDatabaseName("ix_pernas_de_aposta_aposta_multipla_id");

                    b.ToTable("pernas_de_aposta", "apostas");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.ApostasMultiplas.ApostaMultipla", b =>
                {
                    b.HasOne("Oddify.Modules.Apostas.Domain.Bancas.Banca", null)
                        .WithMany()
                        .HasForeignKey("BancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_apostas_multiplas_bancas_banca_id");

                    b.HasOne("Oddify.Modules.Apostas.Domain.PassosDaJornada.PassoDaJornada", null)
                        .WithMany()
                        .HasForeignKey("PassoDaJornadaId")
                        .HasConstraintName("fk_apostas_multiplas_passos_da_jornada_passo_da_jornada_id");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.JornadasDeAlavancagem.JornadaDeAlavancagem", b =>
                {
                    b.HasOne("Oddify.Modules.Apostas.Domain.Bancas.Banca", null)
                        .WithMany()
                        .HasForeignKey("BancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jornadas_de_alavancagem_bancas_banca_id");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.MovimentacoesDaBanca.MovimentacaoDaBanca", b =>
                {
                    b.HasOne("Oddify.Modules.Apostas.Domain.Bancas.Banca", null)
                        .WithMany()
                        .HasForeignKey("BancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_da_banca_bancas_banca_id");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.PassosDaJornada.PassoDaJornada", b =>
                {
                    b.HasOne("Oddify.Modules.Apostas.Domain.JornadasDeAlavancagem.JornadaDeAlavancagem", null)
                        .WithMany()
                        .HasForeignKey("JornadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_passos_da_jornada_jornadas_de_alavancagem_jornada_id");
                });

            modelBuilder.Entity("Oddify.Modules.Apostas.Domain.PernasDeAposta.PernaDeAposta", b =>
                {
                    b.HasOne("Oddify.Modules.Apostas.Domain.ApostasMultiplas.ApostaMultipla", null)
                        .WithMany()
                        .HasForeignKey("ApostaMultiplaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pernas_de_aposta_apostas_multiplas_aposta_multipla_id");
                });
#pragma warning restore 612, 618
        }
    }
}
