<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="FluentAssertions" Version="6.12.2" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Common\Oddify.Common.Domain\Oddify.Common.Domain.csproj" />
    <ProjectReference Include="..\..\src\Common\Oddify.Common.Application\Oddify.Common.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Fixtures\Oddify.Modules.Fixtures.Domain\Oddify.Modules.Fixtures.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Fixtures\Oddify.Modules.Fixtures.Application\Oddify.Modules.Fixtures.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Fixtures\Oddify.Modules.Fixtures.PublicApi\Oddify.Modules.Fixtures.PublicApi.csproj" />
    <ProjectReference Include="..\..\src\Modules\Analise\Oddify.Modules.Analise.Domain\Oddify.Modules.Analise.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Analise\Oddify.Modules.Analise.Application\Oddify.Modules.Analise.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Analise\Oddify.Modules.Analise.PublicApi\Oddify.Modules.Analise.PublicApi.csproj" />
    <ProjectReference Include="..\..\src\Modules\Apostas\Oddify.Modules.Apostas.Domain\Oddify.Modules.Apostas.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Apostas\Oddify.Modules.Apostas.Application\Oddify.Modules.Apostas.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Apostas\Oddify.Modules.Apostas.Presentation\Oddify.Modules.Apostas.Presentation.csproj" />
    <ProjectReference Include="..\..\src\Modules\Users\Oddify.Modules.Users.Domain\Oddify.Modules.Users.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Users\Oddify.Modules.Users.Application\Oddify.Modules.Users.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Users\Oddify.Modules.Users.Presentation\Oddify.Modules.Users.Presentation.csproj" />
    <ProjectReference Include="..\..\src\Modules\Users\Oddify.Modules.Users.IntegrationEvents\Oddify.Modules.Users.IntegrationEvents.csproj" />
  </ItemGroup>

</Project>
