// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oddify.Modules.Fixtures.Infrastructure.Database;

#nullable disable

namespace Oddify.Modules.Fixtures.Infrastructure.Database.Migrations
{
    [DbContext(typeof(FixturesDbContext))]
    [Migration("20260818194403_Mensageria_Espelhar_ModularMonolith")]
    partial class Mensageria_Espelhar_ModularMonolith
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fixtures")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oddify.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOnUtc", "ProcessedOnUtc")
                        .HasDatabaseName("idx_outbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("OccurredOnUtc", "ProcessedOnUtc"), new[] { "Id", "Type", "Content" });

                    b.ToTable("outbox_messages", "fixtures");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.Cotacoes.Cotacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Casa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("casa");

                    b.Property<DateTime>("ColetadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("coletada_em_utc");

                    b.Property<string>("Mercado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mercado");

                    b.Property<decimal>("Odd")
                        .HasColumnType("numeric")
                        .HasColumnName("odd");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.HasKey("Id")
                        .HasName("pk_cotacoes");

                    b.HasIndex("PartidaId")
                        .HasDatabaseName("ix_cotacoes_partida_id");

                    b.ToTable("cotacoes", "fixtures");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.Equipes.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_externo");

                    b.Property<Guid>("LigaId")
                        .HasColumnType("uuid")
                        .HasColumnName("liga_id");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_equipes");

                    b.HasIndex("LigaId")
                        .HasDatabaseName("ix_equipes_liga_id");

                    b.ToTable("equipes", "fixtures");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.Escalacoes.Escalacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<string>("Formacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("formacao");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.Property<string>("Tecnico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tecnico");

                    b.HasKey("Id")
                        .HasName("pk_escalacoes");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_escalacoes_equipe_id");

                    b.HasIndex("PartidaId")
                        .HasDatabaseName("ix_escalacoes_partida_id");

                    b.ToTable("escalacoes", "fixtures");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.EscalacoesDeJogador.EscalacaoJogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EscalacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("escalacao_id");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogador_id");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("posicao");

                    b.Property<bool>("Titular")
                        .HasColumnType("boolean")
                        .HasColumnName("titular");

                    b.HasKey("Id")
                        .HasName("pk_escalacoes_de_jogador");

                    b.HasIndex("EscalacaoId")
                        .HasDatabaseName("ix_escalacoes_de_jogador_escalacao_id");

                    b.HasIndex("JogadorId")
                        .HasDatabaseName("ix_escalacoes_de_jogador_jogador_id");

                    b.ToTable("escalacoes_de_jogador", "fixtures");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.EstatisticasDeEquipe.EstatisticaEquipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<int>("Escanteios")
                        .HasColumnType("integer")
                        .HasColumnName("escanteios");

                    b.Property<int>("Finalizacoes")
                        .HasColumnType("integer")
                        .HasColumnName("finalizacoes");

                    b.Property<int>("Gols")
                        .HasColumnType("integer")
                        .HasColumnName("gols");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.Property<decimal>("Posse")
                        .HasColumnType("numeric")
                        .HasColumnName("posse");

                    b.HasKey("Id")
                        .HasName("pk_estatisticas_de_equipe");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_estatisticas_de_equipe_equipe_id");

                    b.HasIndex("PartidaId")
                        .HasDatabaseName("ix_estatisticas_de_equipe_partida_id");

                    b.ToTable("estatisticas_de_equipe", "fixtures");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.EstatisticasDeJogador.EstatisticaJogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Assistencias")
                        .HasColumnType("integer")
                        .HasColumnName("assistencias");

                    b.Property<int>("Gols")
                        .HasColumnType("integer")
                        .HasColumnName("gols");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogador_id");

                    b.Property<int>("Minutos")
                        .HasColumnType("integer")
                        .HasColumnName("minutos");

                    b.Property<decimal>("Nota")
                        .HasColumnType("numeric")
                        .HasColumnName("nota");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.Property<bool>("Titular")
                        .HasColumnType("boolean")
                        .HasColumnName("titular");

                    b.HasKey("Id")
                        .HasName("pk_estatisticas_de_jogador");

                    b.HasIndex("JogadorId")
                        .HasDatabaseName("ix_estatisticas_de_jogador_jogador_id");

                    b.HasIndex("PartidaId")
                        .HasDatabaseName("ix_estatisticas_de_jogador_partida_id");

                    b.ToTable("estatisticas_de_jogador", "fixtures");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.Jogadores.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_externo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("posicao");

                    b.HasKey("Id")
                        .HasName("pk_jogadores");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_jogadores_equipe_id");

                    b.ToTable("jogadores", "fixtures");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.Ligas.LigaConfigurada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bandeira")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bandeira");

                    b.Property<bool>("Calibrada")
                        .HasColumnType("boolean")
                        .HasColumnName("calibrada");

                    b.Property<decimal>("FatorCasa")
                        .HasColumnType("numeric")
                        .HasColumnName("fator_casa");

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_externo");

                    b.Property<decimal>("MediaDeGols")
                        .HasColumnType("numeric")
                        .HasColumnName("media_de_gols");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_ligas");

                    b.HasIndex("IdExterno")
                        .IsUnique()
                        .HasDatabaseName("ix_ligas_id_externo");

                    b.ToTable("ligas", "fixtures");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.Partidas.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_utc");

                    b.Property<Guid>("EquipeCasaId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_casa_id");

                    b.Property<Guid>("EquipeVisitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_visitante_id");

                    b.Property<int?>("GolsCasa")
                        .HasColumnType("integer")
                        .HasColumnName("gols_casa");

                    b.Property<int?>("GolsVisitante")
                        .HasColumnType("integer")
                        .HasColumnName("gols_visitante");

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_externo");

                    b.Property<Guid>("LigaId")
                        .HasColumnType("uuid")
                        .HasColumnName("liga_id");

                    b.Property<int>("Rodada")
                        .HasColumnType("integer")
                        .HasColumnName("rodada");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<int>("Temporada")
                        .HasColumnType("integer")
                        .HasColumnName("temporada");

                    b.HasKey("Id")
                        .HasName("pk_partidas");

                    b.HasIndex("EquipeCasaId")
                        .HasDatabaseName("ix_partidas_equipe_casa_id");

                    b.HasIndex("EquipeVisitanteId")
                        .HasDatabaseName("ix_partidas_equipe_visitante_id");

                    b.HasIndex("LigaId", "Temporada", "Rodada")
                        .HasDatabaseName("ix_partidas_liga_id_temporada_rodada");

                    b.ToTable("partidas", "fixtures");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.Cotacoes.Cotacao", b =>
                {
                    b.HasOne("Oddify.Modules.Fixtures.Domain.Partidas.Partida", null)
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cotacoes_partidas_partida_id");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.Equipes.Equipe", b =>
                {
                    b.HasOne("Oddify.Modules.Fixtures.Domain.Ligas.LigaConfigurada", null)
                        .WithMany()
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipes_ligas_liga_id");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.Escalacoes.Escalacao", b =>
                {
                    b.HasOne("Oddify.Modules.Fixtures.Domain.Equipes.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_escalacoes_equipes_equipe_id");

                    b.HasOne("Oddify.Modules.Fixtures.Domain.Partidas.Partida", null)
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_escalacoes_partidas_partida_id");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.EscalacoesDeJogador.EscalacaoJogador", b =>
                {
                    b.HasOne("Oddify.Modules.Fixtures.Domain.Escalacoes.Escalacao", null)
                        .WithMany()
                        .HasForeignKey("EscalacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_escalacoes_de_jogador_escalacoes_escalacao_id");

                    b.HasOne("Oddify.Modules.Fixtures.Domain.Jogadores.Jogador", null)
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_escalacoes_de_jogador_jogadores_jogador_id");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.EstatisticasDeEquipe.EstatisticaEquipe", b =>
                {
                    b.HasOne("Oddify.Modules.Fixtures.Domain.Equipes.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estatisticas_de_equipe_equipes_equipe_id");

                    b.HasOne("Oddify.Modules.Fixtures.Domain.Partidas.Partida", null)
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estatisticas_de_equipe_partidas_partida_id");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.EstatisticasDeJogador.EstatisticaJogador", b =>
                {
                    b.HasOne("Oddify.Modules.Fixtures.Domain.Jogadores.Jogador", null)
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estatisticas_de_jogador_jogadores_jogador_id");

                    b.HasOne("Oddify.Modules.Fixtures.Domain.Partidas.Partida", null)
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estatisticas_de_jogador_partidas_partida_id");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.Jogadores.Jogador", b =>
                {
                    b.HasOne("Oddify.Modules.Fixtures.Domain.Equipes.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jogadores_equipes_equipe_id");
                });

            modelBuilder.Entity("Oddify.Modules.Fixtures.Domain.Partidas.Partida", b =>
                {
                    b.HasOne("Oddify.Modules.Fixtures.Domain.Equipes.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeCasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_partidas_equipes_equipe_casa_id");

                    b.HasOne("Oddify.Modules.Fixtures.Domain.Equipes.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_partidas_equipes_equipe_visitante_id");

                    b.HasOne("Oddify.Modules.Fixtures.Domain.Ligas.LigaConfigurada", null)
                        .WithMany()
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partidas_ligas_liga_id");
                });
#pragma warning restore 612, 618
        }
    }
}
