<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Oddify.Common.Application\Oddify.Common.Application.csproj" />
    <ProjectReference Include="..\Oddify.Modules.Analise.Domain\Oddify.Modules.Analise.Domain.csproj" />
    <ProjectReference Include="..\Oddify.Modules.Analise.IntegrationEvents\Oddify.Modules.Analise.IntegrationEvents.csproj" />
    <ProjectReference Include="..\..\Fixtures\Oddify.Modules.Fixtures.PublicApi\Oddify.Modules.Fixtures.PublicApi.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Oddify.UnitTests" />
    <InternalsVisibleTo Include="Oddify.Modules.Analise.Infrastructure" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
</Project>
