// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oddify.Modules.Analise.Infrastructure.Database;

#nullable disable

namespace Oddify.Modules.Analise.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AnaliseDbContext))]
    [Migration("20260817212249_Add_OutboxMessages")]
    partial class Add_OutboxMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analise")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oddify.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOnUtc", "ProcessedOnUtc")
                        .HasDatabaseName("idx_outbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("OccurredOnUtc", "ProcessedOnUtc"), new[] { "Id", "Type", "Content" });

                    b.ToTable("outbox_messages", "analise");
                });

            modelBuilder.Entity("Oddify.Modules.Analise.Domain.Analises.AnaliseDePartida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AprovadaNoFiltro")
                        .HasColumnType("boolean")
                        .HasColumnName("aprovada_no_filtro");

                    b.Property<DateTime>("CriadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em_utc");

                    b.Property<int>("DecisaoDoClaude")
                        .HasColumnType("integer")
                        .HasColumnName("decisao_do_claude");

                    b.Property<string>("JustificativaDoClaude")
                        .HasColumnType("text")
                        .HasColumnName("justificativa_do_claude");

                    b.Property<string>("Mercado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mercado");

                    b.Property<string>("MotivoDoDescarte")
                        .HasColumnType("text")
                        .HasColumnName("motivo_do_descarte");

                    b.Property<decimal>("OddDeMercado")
                        .HasColumnType("numeric")
                        .HasColumnName("odd_de_mercado");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.Property<decimal>("ProbDixonColes")
                        .HasColumnType("numeric")
                        .HasColumnName("prob_dixon_coles");

                    b.Property<decimal>("ProbImplicitaDaOdd")
                        .HasColumnType("numeric")
                        .HasColumnName("prob_implicita_da_odd");

                    b.Property<decimal>("ProbPoissonPura")
                        .HasColumnType("numeric")
                        .HasColumnName("prob_poisson_pura");

                    b.Property<string>("RespostaLlmBruta")
                        .HasColumnType("text")
                        .HasColumnName("resposta_llm_bruta");

                    b.Property<decimal>("Vantagem")
                        .HasColumnType("numeric")
                        .HasColumnName("vantagem");

                    b.Property<string>("VersaoDoPrompt")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("versao_do_prompt");

                    b.HasKey("Id")
                        .HasName("pk_analises_de_partida");

                    b.ToTable("analises_de_partida", "analise");
                });
#pragma warning restore 612, 618
        }
    }
}
