// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oddify.Modules.Analise.Infrastructure.Database;

#nullable disable

namespace Oddify.Modules.Analise.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AnaliseDbContext))]
    [Migration("20260819062437_MirrorDeFixtures")]
    partial class MirrorDeFixtures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analise")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oddify.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("OccurredOnUtc", "ProcessedOnUtc")
                        .HasDatabaseName("idx_inbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("OccurredOnUtc", "ProcessedOnUtc"), new[] { "Id", "Type", "Content" });

                    b.ToTable("inbox_messages", "analise");
                });

            modelBuilder.Entity("Oddify.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOnUtc", "ProcessedOnUtc")
                        .HasDatabaseName("idx_outbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("OccurredOnUtc", "ProcessedOnUtc"), new[] { "Id", "Type", "Content" });

                    b.ToTable("outbox_messages", "analise");
                });

            modelBuilder.Entity("Oddify.Modules.Analise.Domain.Analises.AnaliseDePartida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AprovadaNoFiltro")
                        .HasColumnType("boolean")
                        .HasColumnName("aprovada_no_filtro");

                    b.Property<DateTime>("CriadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em_utc");

                    b.Property<int>("DecisaoDoClaude")
                        .HasColumnType("integer")
                        .HasColumnName("decisao_do_claude");

                    b.Property<string>("JustificativaDoClaude")
                        .HasColumnType("text")
                        .HasColumnName("justificativa_do_claude");

                    b.Property<string>("Mercado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mercado");

                    b.Property<string>("MotivoDoDescarte")
                        .HasColumnType("text")
                        .HasColumnName("motivo_do_descarte");

                    b.Property<decimal>("OddDeMercado")
                        .HasColumnType("numeric")
                        .HasColumnName("odd_de_mercado");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.Property<decimal>("ProbDixonColes")
                        .HasColumnType("numeric")
                        .HasColumnName("prob_dixon_coles");

                    b.Property<decimal>("ProbImplicitaDaOdd")
                        .HasColumnType("numeric")
                        .HasColumnName("prob_implicita_da_odd");

                    b.Property<decimal>("ProbPoissonPura")
                        .HasColumnType("numeric")
                        .HasColumnName("prob_poisson_pura");

                    b.Property<string>("RespostaLlmBruta")
                        .HasColumnType("text")
                        .HasColumnName("resposta_llm_bruta");

                    b.Property<decimal>("Vantagem")
                        .HasColumnType("numeric")
                        .HasColumnName("vantagem");

                    b.Property<string>("VersaoDoPrompt")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("versao_do_prompt");

                    b.HasKey("Id")
                        .HasName("pk_analises_de_partida");

                    b.ToTable("analises_de_partida", "analise");
                });

            modelBuilder.Entity("Oddify.Modules.Analise.Domain.Fixtures.Cotacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Casa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("casa");

                    b.Property<DateTime>("ColetadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("coletada_em_utc");

                    b.Property<string>("Mercado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mercado");

                    b.Property<decimal>("Odd")
                        .HasColumnType("numeric")
                        .HasColumnName("odd");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.HasKey("Id")
                        .HasName("pk_cotacoes");

                    b.HasIndex("PartidaId", "Mercado")
                        .HasDatabaseName("ix_cotacoes_partida_id_mercado");

                    b.ToTable("cotacoes", "analise");
                });

            modelBuilder.Entity("Oddify.Modules.Analise.Domain.Fixtures.Liga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Calibrada")
                        .HasColumnType("boolean")
                        .HasColumnName("calibrada");

                    b.Property<decimal>("FatorCasa")
                        .HasColumnType("numeric")
                        .HasColumnName("fator_casa");

                    b.Property<decimal>("MediaDeGols")
                        .HasColumnType("numeric")
                        .HasColumnName("media_de_gols");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_ligas");

                    b.ToTable("ligas", "analise");
                });

            modelBuilder.Entity("Oddify.Modules.Analise.Domain.Fixtures.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_utc");

                    b.Property<Guid>("EquipeCasaId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_casa_id");

                    b.Property<Guid>("EquipeVisitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_visitante_id");

                    b.Property<int?>("GolsCasa")
                        .HasColumnType("integer")
                        .HasColumnName("gols_casa");

                    b.Property<int?>("GolsVisitante")
                        .HasColumnType("integer")
                        .HasColumnName("gols_visitante");

                    b.Property<Guid>("LigaId")
                        .HasColumnType("uuid")
                        .HasColumnName("liga_id");

                    b.HasKey("Id")
                        .HasName("pk_partidas");

                    b.HasIndex("EquipeCasaId")
                        .HasDatabaseName("ix_partidas_equipe_casa_id");

                    b.HasIndex("EquipeVisitanteId")
                        .HasDatabaseName("ix_partidas_equipe_visitante_id");

                    b.ToTable("partidas", "analise");
                });
#pragma warning restore 612, 618
        }
    }
}
